### ISSUE TITLE
Refactor Css 

### ISSUE THREAD

**Issue by decon-harsh** [JsrEntity/home#4]
The css used is actually written in the index.html page itself . Remove and make a style.css with the written css. Dont forget to link the respective stylesheet.

**Comment by jcads** [comment]
Hi @decon-harsh , I would like to work on this. Could you please assign it to me?

**Comment by decon-harsh** [comment]
Feel free to work and sorry for my poor code.

**Comment by flyajar** [comment]
Hi @decon-harsh I submitted a PR #4 addressing this issue. Kindly check. Thanks!

**Comment by decon-harsh** [comment]
Bro @ralfjayjovenal-cp I appreciate your work but you were not assigned this issue. According to open source rules I can't allow you . Sorry however I will keep this and if the assigned person fails to do so , I will consider this PR! Works ?

**Comment by decon-harsh** [comment]
Closing this
